
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdfzguzhtvdfxvulobyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZnpndXpodHZkZnh2dWxvYnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjE1OTcsImV4cCI6MjA1ODIzNzU5N30.w_Bpv85P1ZO_1zDb8HrLBzJ5vNwvtTvoG0fBckn0K3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'souvieshelf-auth',
      storage: localStorage,
    }
  }
);
