
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrrptkpvpezusuxdnqgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycnB0a3B2cGV6dXN1eGRucWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MzcwMDgsImV4cCI6MjA3OTQxMzAwOH0.wU8sPW09fzoBHGqXes5YQSdpOauVR3W5PS9eMdcU7DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'souvieshelf-auth',
      storage: localStorage,
    }
  }
);
